# Generated by Django 6.0.4 on 2026-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockpricecache_stockhistorycache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
