# Generated by Django 6.0.4 on 2026-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistorycache',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockpricecache',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
